services:
  # Настройка базы данных
  db:
    image: postgres:15
    container_name: vending_db_container
    restart: always
    environment:
      POSTGRES_DB: vending_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d vending_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Настройка твоего приложения
  app:
    build: .
    container_name: vending_app_container
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: vending_db
      DB_USERNAME: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      UPLOAD_PATH: /app/uploads/
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres_data:
